import { Router } from "express";
import { controller } from "./controller.js";
import { validate } from "../../middleware/validate.js";
import { authenticate, requirePermission } from "../../middleware/auth.js";
import { listValidator, updateValidator } from "./validator.js";
const router = Router();
router.get("/me/notifications", authenticate("customer"), validate(listValidator), controller.mine);
router.get("/admin/notifications", authenticate("admin"), requirePermission("support.read"), validate(listValidator), controller.list);
router.patch("/admin/notifications/:id", authenticate("admin"), requirePermission("support.write"), validate(updateValidator), controller.update);
export default router;