import express from "express";
import helmet from "helmet";
import compression from "compression";
import cors from "cors";
import cookieParser from "cookie-parser";
import swaggerUi from "swagger-ui-express";
import { env } from "./config/env.js";
import { requestContext } from "./middleware/requestContext.js";
import { requestLogger } from "./middleware/requestLogger.js";
import { mongoSanitize } from "./middleware/mongoSanitize.js";
import { generalLimiter } from "./middleware/rateLimit.js";
import { errorHandler, notFoundHandler } from "./middleware/errorHandler.js";
import routes from "./routes.js";
import signinRoutes from "./modules/signin/route.js";
import { openapi } from "./docs/openapi.js";
import { metricsSnapshot } from "./services/metrics.service.js";
export const createApp = () => {
  const app = express();
  app.use(requestContext);
  app.use(requestLogger);
  app.use(helmet());
  app.use(compression());
  app.use(cors({ origin: env.CORS_ORIGINS ? env.CORS_ORIGINS.split(",") : true, credentials: true }));
  app.use(cookieParser());
  app.use("/api/v1/payments/webhook", express.raw({ type: "application/json", limit: "1mb" }));
  app.use(express.json({ limit: "2mb" }));
  app.use(express.urlencoded({ extended: true }));
  app.use(mongoSanitize);
  app.use(generalLimiter);
  app.get("/health", (req, res) => res.json({ status: "ok", uptimeSeconds: process.uptime() }));
  app.get("/ready", (req, res) => res.json({ status: "ready", checks: { api: "ok", memory: "ok" } }));
  app.get("/metrics", (req, res) => res.json(metricsSnapshot()));
  app.get("/openapi.json", (req, res) => res.json(openapi));
  app.use("/api-docs", swaggerUi.serve, swaggerUi.setup(openapi));
  app.use("/api/signin", signinRoutes);
  app.use("/api/v1", routes);
  app.use(notFoundHandler);
  app.use(errorHandler);
  return app;
};