import authRoutes from "./modules/auth/route.js";
import signinRoutes from "./modules/signin/route.js";
import usersRoutes from "./modules/users/route.js";
import adminsRoutes from "./modules/admins/route.js";
import propertiesRoutes from "./modules/properties/route.js";
import buyEnquiriesRoutes from "./modules/buyEnquiries/route.js";
import sellRequestsRoutes from "./modules/sellRequests/route.js";
import acquisitionsRoutes from "./modules/acquisitions/route.js";
import salesDealsRoutes from "./modules/salesDeals/route.js";
import visitsRoutes from "./modules/visits/route.js";
import callbacksRoutes from "./modules/callbacks/route.js";
import chatThreadsRoutes from "./modules/chatThreads/route.js";
import interiorLeadsRoutes from "./modules/interiorLeads/route.js";
import supportTicketsRoutes from "./modules/supportTickets/route.js";
import appFeedbackRoutes from "./modules/appFeedback/route.js";
import paymentsRoutes from "./modules/payments/route.js";
import documentsRoutes from "./modules/documents/route.js";
import notificationsRoutes from "./modules/notifications/route.js";
import auditLogsRoutes from "./modules/auditLogs/route.js";
import reportsRoutes from "./modules/reports/route.js";
import searchRoutes from "./modules/search/route.js";
import communicationLogsRoutes from "./modules/communicationLogs/route.js";
import appConfigRoutes from "./modules/appConfig/route.js";
import contentRoutes from "./modules/content/route.js";
import adminSettingsRoutes from "./modules/adminSettings/route.js";
import editLocksRoutes from "./modules/editLocks/route.js";
import { Router } from "express";
const router = Router();
router.use(appConfigRoutes);
router.use(contentRoutes);
router.use(adminSettingsRoutes);
router.use(editLocksRoutes);
router.use(authRoutes);
router.use("/signin", signinRoutes);
router.use(usersRoutes);
router.use(adminsRoutes);
router.use(communicationLogsRoutes);
router.use(propertiesRoutes);
router.use(buyEnquiriesRoutes);
router.use(sellRequestsRoutes);
router.use(acquisitionsRoutes);
router.use(salesDealsRoutes);
router.use(visitsRoutes);
router.use(callbacksRoutes);
router.use(chatThreadsRoutes);
router.use(interiorLeadsRoutes);
router.use(supportTicketsRoutes);
router.use(appFeedbackRoutes);
router.use(paymentsRoutes);
router.use(documentsRoutes);
router.use(notificationsRoutes);
router.use(auditLogsRoutes);
router.use(reportsRoutes);
router.use(searchRoutes);
export default router;